[mypy]
python_version = 3.12
ignore_missing_imports = true
explicit_package_bases = true
exclude = .venv|__pycache__

allow_redefinition = true
check_untyped_defs = false
disallow_untyped_defs = false

